[package]
name = "aoc_2018"
version = "0.1.0"
authors = ["Erik Vroon <erik.vroon22@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.32"
regex = "1.1.0"
chrono = "0.4.6"
itertools = "0.8"