name: C++ tests

# Source: https://github.com/bastianhjaeger/github_actions_gtest_example
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install googletest manually
      run: ./install-googletest.sh

    - name: configure 2020
      run: cd 2020 && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..

    - name: make
      run: cd 2020/build && make -j 8

    - name: Run 2020 tests
      working-directory: 2020/build
      run: ./run_tests
