name: Rust tests

on: [workflow_dispatch]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
        experimental: [false]
        include:
          - toolchain: nightly
            experimental: true

    steps:
      - uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
          components: rustfmt, clippy

      - name: Set up caching
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: 2022 -> rust -> target

      - name: Build binaries
        working-directory: 2022/rust
        run: cargo build --all-targets

      - name: Run cargo-fmt
        working-directory: 2022/rust
        run: cargo-fmt

      - name: Run clippy
        working-directory: 2022/rust
        run: cargo clippy -- --deny warnings

      - name: Run tests
        working-directory: 2022/rust
        run: cargo test
