name: test

# Source: https://github.com/bastianhjaeger/github_actions_gtest_example
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install googletest manually
      run: ./install-googletest.sh
    - uses: actions/checkout@v1
    - name: configure 2020
      run: cd 2020 && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: make
      run: cd 2020/build && make -j 8
    - name: Run 2020 tests
      run: cd /home/runner/work/adventofcode/adventofcode/2020/build && ./run_tests
    - name: Run 2016 tests
      run: cd /home/runner/work/adventofcode/adventofcode/2016 && pytest-3
