name: Python tests

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: sudo apt install python3-pytest && python3 -m pip install -r requirements.txt

      # Old, disabled because they take much time
#    - name: Run 2016 tests
#      working-directory: 2016
#      run: pytest-3
#
#    - name: Run 2018 tests
#      working-directory: 2018/python
#      run: pytest-3

    - name: Run 2021 tests
      working-directory: 2021
      run: pytest-3

    - name: Run 2023 tests
      working-directory: 2023
      run: pytest-3
